#!/bin/sh

run () {
  sudo umount mnt
  sudo rmmod s2fs
  make
  make mkfs.s2fs
  sudo dd if=/dev/zero of=img bs=4096 count=100
  sudo insmod s2fs.ko
  sudo ./mkfs.s2fs img
  sudo mount -o loop -t s2fs img mnt
}

clean () {
  sudo umount mnt
  sudo rmmod s2fs
  make clean
}

mount()
{
  sudo mount -o loop -t s2fs img mnt
}

fs_test() {
  run
  echo "*** TEST START ***"
}

case "$1" in
  clean)
    clean
    ;;
  test)
    mount
    ;;
  *)
    run
    ;;
esac
exit 0
